### PR TITLE
2017Q1.fix.parallelized_tests

### PR DESCRIPTION
**Pull request by phmasek**
All test cases pass in Ubuntu x86_64 when running make -j4

### CODE REVIEW

**Review by chrberger — APPROVED** [review]
Interesting - that was everything that was missing to make it pass?

**Comment by chrberger** [comment]
We will include these changes in the next release.

**Comment by phmasek** [comment]
Yes, seems like a combination of the three changed lines made it work. Been testing back and forth with the different configurations of these lines. This is the only configuration that makes the tests pass (which is logical. Nice to be sure though.). Moving to macos fix for the latest master now.

**Comment by chrberger** [comment]
Perfect

**Pull request merged**
