### PR TITLE
added class simplifying creation of argc and argv

### PR DESCRIPTION
**Pull request by crispin-kirchner**

### CODE REVIEW

**Review by chrberger — APPROVED** [review]

**Review by chrberger — CHANGES_REQUESTED** [review]
@crispin-kirchner As discussed please move to odcore/base and add a testsuite, thanks.

**Comment by chrberger** [comment]
@crispin-kirchner What is the status of this PR?

**Comment by crispin-kirchner** [comment]
Refactored and added testsuite, should be ready to merge

**Review by chrberger — APPROVED** [review]

**Comment by chrberger** [comment]
@crispin-kirchner I have reviewed your changes and re-based your PR to pre-release. Let's sync what further changes to be merged into pre-release to package a new release.

**Comment by crispin-kirchner** [comment]
Thanks ;) I did rebasing to pre-release myself yesterday, did that go wrong?

**Comment by crispin-kirchner** [comment]
And what's the procedure? Am I supposed to hit the "Merge" button now, or will you do that?

**Comment by chrberger** [comment]
It didn’t show up in my GitHub view.

**Comment by chrberger** [comment]
I will do that.

**Comment by crispin-kirchner** [comment]
OK, thanks

**Pull request merged**
