### PR TITLE
2016 q4.feature.odrecinspect

### PR DESCRIPTION
**Pull request by chrberger**
* Improved performance for processing Containers
* Improved performance for deserializing Proto messages
* Extended tool odecintegrity to print statistics about .rec files

### CODE REVIEW

**Comment by chrberger** [comment]
Hi @olbender @fgiaimo @HangYin2015,

I have improved a few essential things in OpenDaVINCI:
- Improved performance for processing Containers
- Improved performance for deserializing Proto messages
- Extended tool odecintegrity to print statistics about .rec files

As the first two are critical for everything else, I would like to have an approval from all three of you before I am going to merge this.

**Review by fgiaimo — APPROVED** [review]

**Comment by chrberger** [comment]
@fgiaimo Thanks for your feedback; @HangYin2015 @olbender may I ask you to have an independent look as well?

**Comment by HangYin2015** [comment]
Just had a look. Have not found any problem yet.

**Comment by chrberger** [comment]
@HangYin2015 Thanks for your comment; @olbender What are your thoughts?

**Review by olbender — APPROVED** [review]

**Comment by chrberger** [comment]
@olbender @HangYin2015 @fgiaimo Thanks for reviewing and approving; I will now merge and release a new version.

**Pull request merged**
